version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: lira_backend_api:${LIRA_BACKEND_API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    
    ports:
    - 8000:${API_PORT}
